In [4]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\samar\miniconda3\lib\site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in c:\users\samar\miniconda3\lib\site-packages (from scikit-learn) (2.4.2)
Requirement already satisfied: scipy>=1.10.0 in c:\users\samar\miniconda3\lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in c:\users\samar\miniconda3\lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\samar\miniconda3\lib\site-packages (from scikit-learn) (3.6.0)

In [8]:
import sys
!{sys.executable} -m pip install scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.8.0-cp314-cp314-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in c:\Users\Samar\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn) (2.4.1)
Collecting scipy>=1.10.0 (from scikit-learn)
  Downloading scipy-1.17.1-cp314-cp314-win_amd64.whl.metadata (60 kB)
Collecting joblib>=1.3.0 (from scikit-learn)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.2.0 (from scikit-learn)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.8.0-cp314-cp314-win_amd64.whl (8.1 MB)
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   ----- ---------------------------------- 1.0/8.1 MB 7.2 MB/s eta 0:00:01
   ------------ --------------------------- 2.6/8.1 MB 6.6 MB/s eta 0:00:01
   ------------------- -------------------- 3.9/8.1 MB 6.7 MB/s eta 0:00:01
   --------------------------- ------------ 5.5/8.1 MB 6.8 MB/s eta 0:00:01
   ---------------------------------- ----- 7.1/8.1 MB 7.0 MB/s eta 0:00:01
   ---------------------------------------- 8.1/8.1 MB 6.8 MB/s  0:00:01
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading scipy-1.17.1-cp314-cp314-win_amd64.whl (37.3 MB)
   ---------------------------------------- 0.0/37.3 MB ? eta -:--:--
   - -------------------------------------- 1.3/37.3 MB 6.7 MB/s eta 0:00:06
   -- ------------------------------------- 2.6/37.3 MB 6.2 MB/s eta 0:00:06
   --- ------------------------------------ 3.7/37.3 MB 6.0 MB/s eta 0:00:06
   ----- ---------------------------------- 4.7/37.3 MB 5.7 MB/s eta 0:00:06
   ------ --------------------------------- 5.8/37.3 MB 5.5 MB/s eta 0:00:06
   ------- -------------------------------- 6.8/37.3 MB 5.5 MB/s eta 0:00:06
   -------- ------------------------------- 8.1/37.3 MB 5.5 MB/s eta 0:00:06
   --------- ------------------------------ 9.2/37.3 MB 5.4 MB/s eta 0:00:06
   ---------- ----------------------------- 10.0/37.3 MB 5.4 MB/s eta 0:00:06
   ----------- ---------------------------- 11.0/37.3 MB 5.3 MB/s eta 0:00:05
   ------------ --------------------------- 12.1/37.3 MB 5.3 MB/s eta 0:00:05
   ------------- -------------------------- 12.8/37.3 MB 5.1 MB/s eta 0:00:05
   -------------- ------------------------- 13.4/37.3 MB 4.9 MB/s eta 0:00:05
   -------------- ------------------------- 13.9/37.3 MB 4.8 MB/s eta 0:00:05
   --------------- ------------------------ 14.4/37.3 MB 4.6 MB/s eta 0:00:05
   ---------------- ----------------------- 15.2/37.3 MB 4.5 MB/s eta 0:00:05
   ---------------- ----------------------- 15.7/37.3 MB 4.4 MB/s eta 0:00:05
   ----------------- ---------------------- 16.5/37.3 MB 4.4 MB/s eta 0:00:05
   ------------------ --------------------- 17.3/37.3 MB 4.3 MB/s eta 0:00:05
   ------------------- -------------------- 18.1/37.3 MB 4.3 MB/s eta 0:00:05
   -------------------- ------------------- 18.9/37.3 MB 4.3 MB/s eta 0:00:05
   -------------------- ------------------- 19.4/37.3 MB 4.2 MB/s eta 0:00:05
   --------------------- ------------------ 19.9/37.3 MB 4.2 MB/s eta 0:00:05
   --------------------- ------------------ 20.4/37.3 MB 4.1 MB/s eta 0:00:05
   ---------------------- ----------------- 21.0/37.3 MB 4.0 MB/s eta 0:00:05
   ----------------------- ---------------- 21.5/37.3 MB 4.0 MB/s eta 0:00:04
   ----------------------- ---------------- 22.0/37.3 MB 3.9 MB/s eta 0:00:04
   ----------------------- ---------------- 22.3/37.3 MB 3.8 MB/s eta 0:00:04
   ------------------------ --------------- 22.5/37.3 MB 3.7 MB/s eta 0:00:04
   ------------------------ --------------- 23.1/37.3 MB 3.6 MB/s eta 0:00:04
   ------------------------- -------------- 23.6/37.3 MB 3.6 MB/s eta 0:00:04
   ------------------------- -------------- 24.1/37.3 MB 3.6 MB/s eta 0:00:04
   -------------------------- ------------- 24.6/37.3 MB 3.6 MB/s eta 0:00:04
   -------------------------- ------------- 24.9/37.3 MB 3.5 MB/s eta 0:00:04
   -------------------------- ------------- 25.2/37.3 MB 3.5 MB/s eta 0:00:04
   --------------------------- ------------ 25.7/37.3 MB 3.4 MB/s eta 0:00:04
   ---------------------------- ----------- 26.2/37.3 MB 3.4 MB/s eta 0:00:04
   ---------------------------- ----------- 26.5/37.3 MB 3.3 MB/s eta 0:00:04
   ---------------------------- ----------- 27.0/37.3 MB 3.3 MB/s eta 0:00:04
   ----------------------------- ---------- 27.3/37.3 MB 3.3 MB/s eta 0:00:04
   ----------------------------- ---------- 27.8/37.3 MB 3.2 MB/s eta 0:00:03
   ------------------------------ --------- 28.3/37.3 MB 3.2 MB/s eta 0:00:03
   ------------------------------ --------- 28.8/37.3 MB 3.2 MB/s eta 0:00:03
   ------------------------------- -------- 29.1/37.3 MB 3.2 MB/s eta 0:00:03
   ------------------------------- -------- 29.4/37.3 MB 3.1 MB/s eta 0:00:03
   ------------------------------- -------- 29.6/37.3 MB 3.1 MB/s eta 0:00:03
   -------------------------------- ------- 30.1/37.3 MB 3.0 MB/s eta 0:00:03
   -------------------------------- ------- 30.4/37.3 MB 3.0 MB/s eta 0:00:03
   -------------------------------- ------- 30.7/37.3 MB 3.0 MB/s eta 0:00:03
   --------------------------------- ------ 30.9/37.3 MB 3.0 MB/s eta 0:00:03
   --------------------------------- ------ 31.5/37.3 MB 2.9 MB/s eta 0:00:02
   ---------------------------------- ----- 32.0/37.3 MB 2.9 MB/s eta 0:00:02
   ---------------------------------- ----- 32.5/37.3 MB 2.9 MB/s eta 0:00:02
   ----------------------------------- ---- 33.0/37.3 MB 2.9 MB/s eta 0:00:02
   ----------------------------------- ---- 33.3/37.3 MB 2.9 MB/s eta 0:00:02
   ----------------------------------- ---- 33.6/37.3 MB 2.9 MB/s eta 0:00:02
   ----------------------------------- ---- 33.6/37.3 MB 2.9 MB/s eta 0:00:02
   ------------------------------------ --- 33.8/37.3 MB 2.8 MB/s eta 0:00:02
   ------------------------------------ --- 34.3/37.3 MB 2.8 MB/s eta 0:00:02
   ------------------------------------- -- 34.6/37.3 MB 2.8 MB/s eta 0:00:01
   ------------------------------------- -- 35.1/37.3 MB 2.7 MB/s eta 0:00:01
   ------------------------------------- -- 35.4/37.3 MB 2.7 MB/s eta 0:00:01
   -------------------------------------- - 35.7/37.3 MB 2.7 MB/s eta 0:00:01
   -------------------------------------- - 35.9/37.3 MB 2.7 MB/s eta 0:00:01
   -------------------------------------- - 36.2/37.3 MB 2.7 MB/s eta 0:00:01
   ---------------------------------------  36.4/37.3 MB 2.6 MB/s eta 0:00:01
   ---------------------------------------  37.0/37.3 MB 2.6 MB/s eta 0:00:01
   ---------------------------------------  37.2/37.3 MB 2.6 MB/s eta 0:00:01
   ---------------------------------------- 37.3/37.3 MB 2.6 MB/s  0:00:14
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, joblib, scikit-learn

   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ---------------------------------------- 4/4 [scikit-learn]

Successfully installed joblib-1.5.3 scikit-learn-1.8.0 scipy-1.17.1 threadpoolctl-3.6.0

In [9]:
import sklearn
print(sklearn.__version__)

1.8.0

In [10]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

In [11]:
data = pd.read_csv('data.csv')
data

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num
0,28,1,2,130,132,0,2,185,0,0.0,?,?,?,0
1,29,1,2,120,243,0,0,160,0,0.0,?,?,?,0
2,29,1,2,140,?,0,0,170,0,0.0,?,?,?,0
3,30,0,1,170,237,0,1,170,0,0.0,?,?,6,0
4,31,0,2,100,219,0,1,150,0,0.0,?,?,?,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
289,52,1,4,160,331,0,0,94,1,2.5,?,?,?,1
290,54,0,3,130,294,0,1,100,1,0.0,2,?,?,1
291,56,1,4,155,342,1,0,150,1,3.0,2,?,?,1
292,58,0,2,180,393,0,0,110,1,1.0,2,?,7,1
293,65,1,4,130,275,0,1,115,1,1.0,2,?,?,1

In [12]:
data.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num
0,28,1,2,130,132,0,2,185,0,0.0,?,?,?,0
1,29,1,2,120,243,0,0,160,0,0.0,?,?,?,0
2,29,1,2,140,?,0,0,170,0,0.0,?,?,?,0
3,30,0,1,170,237,0,1,170,0,0.0,?,?,6,0
4,31,0,2,100,219,0,1,150,0,0.0,?,?,?,0

In [13]:
data.tail()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num
289,52,1,4,160,331,0,0,94,1,2.5,?,?,?,1
290,54,0,3,130,294,0,1,100,1,0.0,2,?,?,1
291,56,1,4,155,342,1,0,150,1,3.0,2,?,?,1
292,58,0,2,180,393,0,0,110,1,1.0,2,?,7,1
293,65,1,4,130,275,0,1,115,1,1.0,2,?,?,1

In [14]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 294 entries, 0 to 293
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   age         294 non-null    int64
 1   sex         294 non-null    int64
 2   cp          294 non-null    int64
 3   trestbps    294 non-null    str
 4   chol        294 non-null    str
 5   fbs         294 non-null    str
 6   restecg     294 non-null    str
 7   thalach     294 non-null    str
 8   exang       294 non-null    str
 9   oldpeak     294 non-null    float64
 10  slope       294 non-null    str
 11  ca          294 non-null    str
 12  thal        294 non-null    str
 13  num         294 non-null    int64
dtypes: float64(1), int64(4), str(9)
memory usage: 32.3 KB

In [15]:
data.describe()

              age         sex          cp     oldpeak  num
count  294.000000  294.000000  294.000000  294.000000  294.000000
mean    47.826531    0.724490    2.982993    0.586054    0.360544
std      7.811812    0.447533    0.965117    0.908648    0.480977
min     28.000000    0.000000    1.000000    0.000000    0.000000
25%     42.000000    0.000000    2.000000    0.000000    0.000000
50%     49.000000    1.000000    3.000000    0.000000    0.000000
75%     54.000000    1.000000    4.000000    1.000000    1.000000
max     66.000000    1.000000    4.000000    5.000000    1.000000

In [16]:
data.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'num       '],
      dtype='str')

In [20]:
data.columns = data.columns.str.strip()
data = data.drop(['ca','thal'], axis=1)
data.head()

   age  sex  cp trestbps chol fbs restecg thalach exang  oldpeak slope  num
0   28    1   2      130  132   0       2     185     0      0.0     ?    0
1   29    1   2      120  243   0       0     160     0      0.0     ?    0
2   29    1   2      140    ?   0       0     170     0      0.0     ?    0
3   30    0   1      170  237   0       1     170     0      0.0     ?    0
4   31    0   2      100  219   0       1     150     0      0.0     ?    0

In [21]:
data.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'num'],
      dtype='str')

In [ ]:
data = data.replace('?',np.nan)

In [23]:
data['slope'] = pd.to_numeric(data['slope'])

In [28]:
data['slope'] = data['slope'].fillna(data['slope'].median())

In [29]:
data['slope'].isnull().sum()

np.int64(0)

In [31]:
data.dtypes

age           int64
sex           int64
cp            int64
trestbps        str
chol            str
fbs             str
restecg         str
thalach         str
exang           str
oldpeak     float64
slope       float64
num           int64
dtype: object

In [32]:
data = data.apply(pd.to_numeric)

In [33]:
data = data.fillna(data.median())

In [34]:
data.dtypes

age           int64
sex           int64
cp            int64
trestbps    float64
chol        float64
fbs         float64
restecg     float64
thalach     float64
exang       float64
oldpeak     float64
slope       float64
num           int64
dtype: object

In [35]:
X = data.drop("num", axis=1)
y = data["num"]

In [36]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [37]:
print(X.shape)
print(y.shape)

(294, 11)
(294,)

In [38]:
print(X_train.shape)
print(X_test.shape)

(235, 11)
(59, 11)

In [39]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [40]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

model.fit(X_train, y_train)

LogisticRegression()

In [41]:
y_pred = model.predict(X_test)

In [42]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print("Accuracy:", accuracy_score(y_test, y_pred))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("Classification Report:")
print(classification_report(y_test, y_pred))

Accuracy: 0.8305084745762712
Confusion Matrix:
[[32  6]
 [ 4 17]]
Classification Report:
              precision    recall  f1-score   support

           0       0.89      0.84      0.86        38
           1       0.74      0.81      0.77        21

    accuracy                           0.83        59
   macro avg       0.81      0.83      0.82        59
weighted avg       0.84      0.83      0.83        59

In [43]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier()

rf.fit(X_train, y_train)

rf_pred = rf.predict(X_test)

print("Random Forest Accuracy:", accuracy_score(y_test, rf_pred))

Random Forest Accuracy: 0.847457627118644

In [44]:
import joblib

joblib.dump(model, "heart_disease_model.pkl")

['heart_disease_model.pkl']